# Generated by Django 3.1.3 on 2021-04-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrimesData',
            fields=[
                ('id', models.TextField(db_column='ID', primary_key=True, serialize=False)),
                ('case_number', models.TextField(blank=True, db_column='Case Number', null=True)),
                ('date', models.TextField(blank=True, db_column='Date', null=True)),
                ('block', models.TextField(blank=True, db_column='Block', null=True)),
                ('iucr', models.TextField(blank=True, db_column='IUCR', null=True)),
                ('primary_type', models.TextField(blank=True, db_column='Primary Type', null=True)),
                ('district', models.IntegerField(blank=True, db_column='District', null=True)),
                ('community_area', models.FloatField(blank=True, db_column='Community Area', null=True)),
                ('x_coordinate', models.FloatField(blank=True, db_column='X Coordinate', null=True)),
                ('y_coordinate', models.FloatField(blank=True, db_column='Y Coordinate', null=True)),
            ],
            options={
                'db_table': 'crimes_data',
                'managed': False,
            },
        ),
    ]
