# Generated by Django 3.1.3 on 2021-04-10 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bigbrother', '0002_prediction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prediction',
            options={},
        ),
    ]
